/**
  * @file hts221_dev.h
  * @author generated by mrt-device tool
  * @brief values and constants for the HTS221 device
  * 
  */

#define HTS_I2C_ADDRESS 0xBE


/*******************************************************************************
  Register Addresses                                                                              
*******************************************************************************/

#define HTS_REG_WHO_AM_I_ADDR                       0x0F
#define HTS_REG_AV_CONF_ADDR                       0x10
#define HTS_REG_CTRL1_ADDR                       0x20
#define HTS_REG_CTRL2_ADDR                       0x21
#define HTS_REG_CTRL3_ADDR                       0x22
#define HTS_REG_STATUS_ADDR                       0x27
#define HTS_REG_HUMIDITY_OUT_ADDR                       0x28
#define HTS_REG_TEMP_OUT_ADDR                       0x2A
#define HTS_REG_H0_RH_X2_ADDR                       0x30
#define HTS_REG_H1_RH_X2_ADDR                       0x31
#define HTS_REG_T0_DEGC_X8_ADDR                       0x32
#define HTS_REG_T1_DEGC_X8_ADDR                       0x33
#define HTS_REG_T1T0_MSB_ADDR                       0x35
#define HTS_REG_H0_T0_OUT_ADDR                       0x36
#define HTS_REG_H1_T0_OUT_ADDR                       0x3A
#define HTS_REG_T0_OUT_ADDR                       0x3C
#define HTS_REG_T1_OUT_ADDR                       0x3E


/*******************************************************************************
  Flags                                                                              
*******************************************************************************/

/* STATUS Register Flags */
#define HTS_STATUS_TEMP_READY                       0x01
#define HTS_STATUS_HUM_READY                       0x02


/*******************************************************************************
  Flags Values                                                                              
*******************************************************************************/

/* CTRL1 Register Fields */
  /* CTRL1 -> ODR */
  #define HTS_CTRL1_ODR_MASK        0x07
  #define HTS_CTRL1_ODR_ONESHOT      0x00
  #define HTS_CTRL1_ODR_1HZ      0x01
  #define HTS_CTRL1_ODR_7HZ      0x02
  #define HTS_CTRL1_ODR_12_5HZ      0x03

/*******************************************************************************
  Default Values                                                                              
*******************************************************************************/

#define HTS_WHO_AM_I_DEFAULT  0xBC

/*******************************************************************************
  Flag Set/Clear/Check                                                                             
*******************************************************************************/

/**
  *@brief sets flags on device
  *@param dev ptr to HTS221 device
  *@param reg ptr to register definition
  *@param mask mask of flags to set
  */
#define hts_set_flag(dev, reg, mask) regdev_set_flags(&(dev)->mRegDev,(reg), (mask))

/**
  *@brief clears flags on device
  *@param dev ptr to HTS221 device
  *@param reg ptr to register definition
  *@param mask mask of flags to set
  */
#define hts_clear_flag(dev, reg, mask) regdev_clear_flags(&(dev)->mRegDev,(reg), (mask))

/**
  *@brief checks flags on device
  *@param dev ptr to HTS221 device
  *@param reg ptr to register definition
  *@param mask mask of flags to set
  *@return true if all flags in mask are set 
  *@return false if any flags in mask are not set
  */
#define hts_check_flag(dev, reg, mask) regdev_check_flags(&(dev)->mRegDev,(reg), (mask))

/*******************************************************************************
  Field Getters                                                                              
*******************************************************************************/

/**
 * @brief reads the ODR field from the device 
 * @param dev ptr to HTS221 device
 * @return HTS_CTRL1_ODR_ONESHOT readings must be requested
 * @return HTS_CTRL1_ODR_1HZ 1 hz sampling
 * @return HTS_CTRL1_ODR_7HZ 7 hz sampling
 * @return HTS_CTRL1_ODR_12_5HZ 12.5 hz sampling
 */
#define hts_get_ctrl1_odr(dev) regdev_read_field(dev->mRegDev, &(dev)->mCtrl1, HTS_CTRL1_ODR_MASK )


/*******************************************************************************
  Field Setters                                                                              
*******************************************************************************/

/**
 * @brief writes the ODR field from the device 
 * @param dev ptr to HTS221 device
 * @option HTS_CTRL1_ODR_ONESHOT readings must be requested
 * @option HTS_CTRL1_ODR_1HZ 1 hz sampling
 * @option HTS_CTRL1_ODR_7HZ 7 hz sampling
 * @option HTS_CTRL1_ODR_12_5HZ 12.5 hz sampling
 */
#define hts_set_ctrl1_odr(dev) regdev_write_field(dev->mRegDev, &(dev)->mCtrl1, HTS_CTRL1_ODR_MASK )
